### ISSUE TITLE
Image Search

### ISSUE THREAD

**Issue by neerajakshid** [neerajakshid/Week-2---Image-Search#1]
My Image Search app is complete, please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Excellent work overall!!! A few notes after checking out the code:
- Great work on packaging the code correctly
- Good job using Parcelable instead of Serializable ([benefits](http://stackoverflow.com/a/5551155))
- Good job using the ConnectivityManager to check for network availability and notifying user about failure
- Great job implementing SettingsDialog for filters.
- Good job using StaggeredGridView and TouchImageView for enhancing UI/UX
- Good to see you added Search using the action bar and correctly implemented sharing 
- Good to see JSON deserializing logic in the model object. (Consider adding null checks)

Also, here's a more detailed [Project 2 Feedback Guide here](https://gist.github.com/nesquena/44091e4727b154d04269) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](https://gist.github.com/nesquena/44091e4727b154d04269) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.

**Comment by neerajakshid** [comment]
Thanks for the review :) 

I have a question as follows:
I am trying to convert images from px to dp using the following function programmatically in java using the following method:
// Converting px to dp
    public static int convertPixelsToDp(final Context context, final float px ){
        DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics();
        return (int) ((px/displayMetrics.density)+0.5);
    }

And I  am using this method for width and height while loading the thumbnail images in the load(width, height) attribute of Picassa in the Adapter class as follows:

 DimmensionsHelper dimHelper = new DimmensionsHelper();
            int tbHeight = dimHelper.convertPixelsToDp(getContext(), imageInfo.pxTbHeight);
            int tbWidth = dimHelper.convertPixelsToDp(getContext(), imageInfo.pxTbWidth);
            viewHolder.ivImageItem.setImageResource(0);
            Picasso.with(getContext()).load(imageInfo.thumbUrl).resize(tbWidth,tbHeight).placeholder(R.mipmap.ic_launcher).into(viewHolder.ivImageItem);

Then I notice the images are blurred. Any idea what am I doing wrong in the conversion?

@codepathreview @nathan

**Comment by nidhi1608** [comment]
The problem is that you are trying to match dp in ImageView to px in bitmap by converting the bitmap to dp but behind the scenes, the ImageView is also comprised of pixels. dp is just a convenience for representing  view that is approximately the same size across different devices. By converting to dp, you are resizing the image down causing the blurring. You can set the image directly to the ImageView to rectify this. In order to support multiple screen resolutions you would create alternative bitmap resources tailored to each of the generalized density buckets: low, medium, high and extra-high density. See [working with the ImageView](http://guides.codepath.com/android/Working-with-the-ImageView) guide to learn more about supporting different densities.

**Comment by neerajakshid** [comment]
Got it!! Thanks for the solution Nidhi..
